### ISSUE TITLE
System.Text.Encodings.Web Vulnerability

### ISSUE THREAD

**Issue by BlakeItOut** [RockLib/RockLib.Configuration#69]
There is a vulnerability identified by snyk: https://app.snyk.io/vuln/SNYK-DOTNET-SYSTEMTEXTENCODINGSWEB-1253267 that can be addressed with a simple version update.

**Comment by bfriesen** [comment]
I'm confused, we don't take a dependency on System.Text.Encodings.Web. Where is the vulnerability here?

**Comment by BlakeItOut** [comment]
Detailed paths
Introduced through: project@* › RockLib.Configuration@2.5.2 › Microsoft.Extensions.Configuration.Json@5.0.0 › System.Text.Json@5.0.0 › System.Text.Encodings.Web@5.0.0

**Comment by bfriesen** [comment]
We'll need to be sure to propagate to satellite libraries ([like health checks](https://github.com/RockLib/RockLib.HealthChecks/issues/16)) after fixing and publishing this.

**Comment by bfriesen** [comment]
Hmm, after digging into this further, it doesn't look like there actually _is_ a dependency on System.Text.Encodings.Web version 5.0.0 from RockLib.Configuration.

[RockLib.Configuration version 2.5.2](https://www.nuget.org/packages/RockLib.Configuration/2.5.2) has multiple targets (`.NETFramework 4.5.1`, `.NETFramework 4.6.2`, `.NETStandard 1.6`, `.NETStandard 2.0`, and `net5.0`), but only the `net5.0` target has a dependency on Microsoft.Extensions.Configuration.Json version 5.0.0 (the other targets have a dependency on earlier versions of M.E.C.J.).

[Microsoft.Extensions.Configuration.Json version 5.0.0](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Json/5.0.0) also has multiple targets (`.NETFramework 4.6.1`, `.NETStandard 2.0`, `.NETStandard 2.1`, and `net5.0`). However, all of the targets _except_ `net5.0` have a dependency on System.Text.Json version 5.0.0. And it's System.Text.Json versions < 5.0.2 that have the dependency on System.Text.Encodings.Web version 5.0.0, which has the vulnerability.
