### ISSUE TITLE
There is a severe memory leak in RockLib.Configuration.ObjectFactory

### ISSUE THREAD

**Issue by jerryk414** [RockLib/RockLib.Configuration#82]
### Overview
When using `RockLib.Configuration.ObjectFactory`, under certain circumstances, a memory leak can occur. This memory leak appears to only happen when setting up automatic config file reloading via `ConfigReloadingProxyFactory`. (`CreateReloadingProxy` specifically)

### Details
It's hard to say when this problem was introduced - i've been able to verify that it is at least occurring in 2.x versions as well as the latest 4.x release. Other than that, I have not confirmed, but it's highly likely that this is a problem there as well.

The problem occurs when the type configured to be setup as a reloadable type implements `IDisposable` (e.g. `RockLib.Logging.ILogger`).

What happens is that, when you request a reloadable configuration object, under the covers a type is dynamically created using a bunch of fancy hand-waving with IL and reflection to get an actual instance of a new type of object. As a consumer you would request an object of type `IMyConfigType`, and you would indeed be returned with an instance of that interface.

So using `RockLib.Logging` as an example, if you would like to create an instance of `ILogger` that reloads on-demand any time the `appsettings.json` file is changed, you would call into this method. Prior to calling this method, you would need to setup a default type to be passed in that acts as a mapping between the interface and the actual concrete type you're using to house your config data (i.e. `ILogger` and `Logger`). When you call `ConfigReloadingProxyFactory.CreateReloadingProxy`, what it actually returns is a completely new type that implements `ILogger`, and all of the implementations of `ILogger` defined in `Logger` have been magically copied to that new object.

Using a more simple example of `IMyCustomConfigType` and `MyCustomConfigType`, you may be returned an object (`SuperSpecialDynamicallyCreatedType`) that looks something like this:
```csharp
public interface IMyCustomConfigType
{
  void MySpecialMethod();
}

public class MyCustomConfigType : IMyCustomConfigType
{
   public void MySpecialMethod()
   {
     Console.WriteLine((1 + 1) == 11);
   }
}

public class SuperSpecialDynamicallyCreatedType<IMyCustomConfigType> : ConfigReloadingProxy, IMyCustomConfigType
{
   public void MySpecialMethod()
   {
     Console.WriteLine((1 + 1) == 11);
   }
}
```

This is cool, but there are actually three problems.

1) The `SuperSpeciallyDynamicallyCreatedType` is actually based on an existing type - `ConfigReloadingProxy`. And `ConfigReloadingProxy` actually creates and (currently) does not keep track of, nor dispose of an `IDisposable` object. In the constructor for this class, there is the line:
```csharp
ChangeToken.OnChange(section.GetReloadToken, () => ReloadObject(false));
```
2) Let's same problem 1 is fixed, you still have the other problem that there is no requirement that the type being created is even disposable. So even if you did update the `Dispose` method on `ConfigReloadingProxy` to dispose of the change token disposable, the `Dispose` method may not be called when you want it to - or may not even be called at all.
3) Even if you enforced that any type you're creating for this dynamic reloading proxy were to be `IDisposable`, there's an even stranger thing. When the super special dynamic type is created, the `Dispose` method is copied from the implementation type.. which leads to a problem where the base class `Dispose` method is hidden, and it never gets called.

Fortunately, it appears that the fix for this is pretty easy:
1) Update the `ConfigReloadingProxy` to keep track of and dispose of the `IDisposable` returned from `ChangeToken.OnChange`
2) Enforce that the interface types passed into the `CreateReloadingProxy` method MUST implement `IDisposable`
3) Do not copy the `Dispose` method from the implementation type to the dynamic type - let the base class `CreateReloadingProxy.Dispose()` take care of it.

**Comment by jabaran** [comment]
@jerryk414 , nice write up. 

When I was talking with the team I heard this was eating a fair amount of memory and seemed like it was causing some nasty production related memory problems. I was wondering if the reload was occurring at in appropriate times as well, or if there deployments of just configurations files that was appropriately causing the reloads.

**Comment by jkrmo** [comment]
@JasonBock This issue can be closed now, right?

**Comment by JasonBock** [comment]
Yep.
